print("welcome to the band name generator")
city=input("which city did you grow up in?\n")
pet=input("what is your pet's name?\n") 
band_name= (city  +" " + pet)
print(f"your band name could be {band_name}")